<h1 align="center">Data Analysis using Pandas and Numpy </h1>

In [1]:
import pandas as pd
import numpy as np

## categorical()

#### Qn. Replace PClass values with categorical labels

In [2]:
titanic_train = pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",
                           sep='\t') 
titanic_train.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [9]:
#create categorial object
Pcat = pd.Categorical(titanic_train['Pclass'])
print(type(Pcat))
print(Pcat)

#rename values of categorical object
catCol = Pcat.rename_categories(['Class A', 'Class B', 'Class C'])
print(catCol)

#replace df col with new col
titanic_train['Pclass'] = catCol
titanic_train.head(3)

<class 'pandas.core.arrays.categorical.Categorical'>
[3, 1, 3, 1, 3, ..., 1, 3, 3, 3, 1]
Length: 156
Categories (3, int64): [1, 2, 3]
[Class C, Class A, Class C, Class A, Class C, ..., Class A, Class C, Class C, Class C, Class A]
Length: 156
Categories (3, object): [Class A, Class B, Class C]


PassengerId  Survived   Pclass  \
0            1         0  Class C   
1            2         1  Class A   
2            3         1  Class C   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

#### Qn. Extract only the char value from the Cabin column

In [22]:
#check the 'Cabin col values'
print(titanic_train['Cabin'].unique())

print(titanic_train.dtypes)

#convert col to str
converted = titanic_train['Cabin'].astype(str)
type(converted[1])
converted.head(3)

#create new col with extracted values
newCol = [val[0] for val in converted]

titanic_train['CabinNew'] = newCol
titanic_train.head(3)

[nan 'C85' 'C123' 'E46' 'G6' 'C103' 'D56' 'A6' 'C23 C25 C27' 'B78' 'D33'
 'B30' 'C52' 'B28' 'C83' 'F33' 'F G73' 'E31' 'A5' 'D10 D12' 'D26' 'C110'
 'B58 B60' 'E101' 'F E69' 'D47' 'B86' 'F2' 'C2']
PassengerId       int64
Survived          int64
Pclass         category
Name             object
Sex              object
Age             float64
SibSp             int64
Parch             int64
Ticket           object
Fare            float64
Cabin            object
Embarked         object
dtype: object


PassengerId  Survived   Pclass  \
0            1         0  Class C   
1            2         1  Class A   
2            3         1  Class C   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked CabinNew  
0      0         A/5 21171   7.2500   NaN        S        n  
1      0          PC 17599  71.2833   C85        C        C  
2      0  STON/O2. 3101282   7.9250   NaN        S        n

#### Qn. Extract the person name who paid the max fare

In [31]:
#Finding max fare
print(max(titanic_train['Fare']))

#find index of max fare
index = np.where(titanic_train['Fare']==max(titanic_train['Fare']))
print(index)

#print rows at those indexes
print(titanic_train.iloc[index][['Name','Fare']])
titanic_train.iloc[index]

263.0
(array([27, 88], dtype=int64),)
                              Name   Fare
27  Fortune, Mr. Charles Alexander  263.0
88      Fortune, Miss. Mabel Helen  263.0


PassengerId  Survived   Pclass                            Name     Sex  \
27           28         0  Class A  Fortune, Mr. Charles Alexander    male   
88           89         1  Class A      Fortune, Miss. Mabel Helen  female   

     Age  SibSp  Parch Ticket   Fare        Cabin Embarked CabinNew  
27  19.0      3      2  19950  263.0  C23 C25 C27        S        C  
88  23.0      3      2  19950  263.0  C23 C25 C27        S        C

#### Qn. Find the family with maximum members

In [37]:
max_family_size = max(titanic_train['SibSp']+titanic_train['Parch'])
print(max_family_size)

indexes = np.where((titanic_train['SibSp']+titanic_train['Parch'])==max_family_size)
titanic_train.iloc[indexes]

7


PassengerId  Survived   Pclass                                Name  \
59           60         0  Class C  Goodwin, Master. William Frederick   
71           72         0  Class C          Goodwin, Miss. Lillian Amy   

       Sex   Age  SibSp  Parch   Ticket  Fare Cabin Embarked CabinNew  
59    male  11.0      5      2  CA 2144  46.9   NaN        S        n  
71  female  16.0      5      2  CA 2144  46.9   NaN        S        n

#### Qn. Create a dataframe with random values

In [38]:
#creating dataframe with random values
from numpy.random import randn as rn
#to prevent changing of random values
np.random.seed(101)
matrix_data = rn(5,4) #5 rows,4 columns
row_labels = ['A','B','C','D','E']
column_headings = ['W','X','Y','Z']

df = pd.DataFrame(matrix_data,row_labels,column_headings)
print("\nThe data frame looks like\n",'-'*45, sep='')
df


The data frame looks like
---------------------------------------------


W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [40]:
#for df with int values between 10 and 99
from numpy.random import randint as ri
#to prevent changing of random values
np.random.seed(101)
matrix_data = ri(10,99,(5,4)) #5 rows,4 columns, values between 10 and 99
row_labels = ['A','B','C','D','E']
column_headings = ['W','X','Y','Z']

df = pd.DataFrame(matrix_data,row_labels,column_headings)
print("\nThe data frame looks like\n",'-'*45, sep='')
df


The data frame looks like
---------------------------------------------


W   X   Y   Z
A  21  91  80  73
B  97  85  19  87
C  50  14  73  50
D  70  74  15  22
E  50  59  93  18

#### Qn. Access elements of df using different ways

In [54]:
#Access row with index C
print(df.loc['C'])
print(df.iloc[2])

print('\nRows C and D\n',df.loc[['C','D']])
#Access single column with label Z
print("\nelements of col Z\n","-"*25,"\n",df['Z'])

#Access multiple columns
print(df[['X','Y']])


W    50
X    14
Y    73
Z    50
Name: C, dtype: int32
W    50
X    14
Y    73
Z    50
Name: C, dtype: int32

Rows C and D
     W   X   Y   Z
C  50  14  73  50
D  70  74  15  22

elements of col Z
 ------------------------- 
 A    73
B    87
C    50
D    22
E    18
Name: Z, dtype: int32
    X   Y
A  91  80
B  85  19
C  14  73
D  74  15
E  59  93


In [60]:
print("Original data frame\n",df)
print("\nAfter subsetting\n",df.loc[['A','B'],['Z','W']])
print("\nAnother way of subsetting\n",df.loc[['A','B']][['Z','W']])


Original data frame
     W   X   Y   Z
A  21  91  80  73
B  97  85  19  87
C  50  14  73  50
D  70  74  15  22
E  50  59  93  18

After subsetting
     Z   W
A  73  21
B  87  97

Another way of subsetting
     Z   W
A  73  21
B  87  97


In [61]:
#iloc can be used in a similar way, but with numerical indexes
df.iloc[[0,4],[0,3]]

W   Z
A  21  73
E  50  18

In [62]:
#all rows, only col X and Y
df.loc[:,['X','Z']]

X   Z
A  91  73
B  85  87
C  14  50
D  74  22
E  59  18

In [63]:
df.loc[::-1,['X','Z']]

X   Z
E  59  18
D  74  22
C  14  50
B  85  87
A  91  73

In [75]:
#intersection of a row and column
df.loc['C','Z']

50

In [64]:
print("\nThe 'X' column accessed by DOT method (NOT recommended)\n",'-'*55, sep='')
print(df["X"])
df.X


The 'X' column accessed by DOT method (NOT recommended)
-------------------------------------------------------
A    91
B    85
C    14
D    74
E    59
Name: X, dtype: int32


A    91
B    85
C    14
D    74
E    59
Name: X, dtype: int32

#### Qn. Access df elements based on condition

In [76]:
df[df>50]

W     X     Y     Z
A   NaN  91.0  80.0  73.0
B  97.0  85.0   NaN  87.0
C   NaN   NaN  73.0   NaN
D  70.0  74.0   NaN   NaN
E   NaN  59.0  93.0   NaN

In [82]:
df[df['X']>80]

W   X   Y   Z
A  21  91  80  73
B  97  85  19  87

#### Qn. Add a new column to the df that contains sum of values of col X and Z

In [69]:
print("\nA column is created by assigning it in relation to an existing column\n",'-'*75, sep='')
df['New'] = df['X']+df['Z']
df['New (Sum of X and Z)'] = df['X']+df['Z']
print(df)


A column is created by assigning it in relation to an existing column
---------------------------------------------------------------------------
    W   X   Y   Z  New (Sum of X and Z)  New
A  21  91  80  73                   164  164
B  97  85  19  87                   172  172
C  50  14  73  50                    64   64
D  70  74  15  22                    96   96
E  50  59  93  18                    77   77


#### Qn. Delete the newly added column

In [71]:
print("\nA column is dropped by using df.drop() method\n",'-'*55, sep=' ')
 # Notice the axis=1 option, axis = 0 is default, so one has to change it to 1
df.drop('New (Sum of X and Z)', axis=1,inplace=True)
df


A column is dropped by using df.drop() method
 -------------------------------------------------------


W   X   Y   Z
A  21  91  80  73
B  97  85  19  87
C  50  14  73  50
D  70  74  15  22
E  50  59  93  18

#### Qn. Delete the rows C and D

In [73]:
print("\nA row (index) is dropped by using df.drop() method and axis=0\n",'-'*65, sep='')
df.drop(['C','D'])


A row (index) is dropped by using df.drop() method and axis=0
-----------------------------------------------------------------


W   X   Y   Z
A  21  91  80  73
B  97  85  19  87
E  50  59  93  18

#### Qn. Create a df using matrix

In [84]:
#create df from matrix
import pandas as pd 
import numpy as np
matrix_data = np.matrix('22,66,140;42,70,148;30,62,125;35,68,160;25,62,152')
print(matrix_data)

row_labels = ['A','B','C','D','E']
column_headings = ['Age', 'Height', 'Weight']
df1 = pd.DataFrame(data=matrix_data, index=row_labels, columns=column_headings)
print("\nA new DataFrame\n",'-'*25, sep='')
print(df1)

[[ 22  66 140]
 [ 42  70 148]
 [ 30  62 125]
 [ 35  68 160]
 [ 25  62 152]]

A new DataFrame
-------------------------
   Age  Height  Weight
A   22      66     140
B   42      70     148
C   30      62     125
D   35      68     160
E   25      62     152


#### Qn. Filter data using condition

In [86]:
#filtering data from df
print("\nRows with Height > 65 inch\n",'-'*35, sep='')
df1[df1['Height']>65]


Rows with Height > 65 inch
-----------------------------------


Age  Height  Weight
A   22      66     140
B   42      70     148
D   35      68     160

In [87]:
#Specifying multiple conditions
booldf1 = df1['Height']>65
booldf2 = df1['Weight']>145

print("\nRows with Height > 65 inch and Weight >145 lbs\n",'-'*55, sep='')
print(df[(booldf1) & (booldf2)])


Rows with Height > 65 inch and Weight >145 lbs
-------------------------------------------------------
    W   X   Y   Z
B  97  85  19  87
D  70  74  15  22


In [88]:
print("\nDataFrame with only Age and Weight columns whose Height > 65 inch\n",'-'*68, sep='')
df1[booldf1][['Age','Weight']]


DataFrame with only Age and Weight columns whose Height > 65 inch
--------------------------------------------------------------------


Age  Weight
A   22     140
B   42     148
D   35     160