<h1 align='center'> Numpy methods </h1>

In [2]:
import numpy as np
import pandas as pd

## arange()

In [9]:
#range() like function that accepts float 
print(np.arange(5))
np.arange(0.1,0.9,0.2)

[0 1 2 3 4]


array([0.1, 0.3, 0.5, 0.7])

In [8]:
np.arange(2,1,-0.3)

array([2. , 1.7, 1.4, 1.1])

## array()

In [3]:
a = np.array([2,3,4])
print(type(a))
a

<class 'numpy.ndarray'>


array([2, 3, 4])

In [4]:
np.array(['sdf',4,5.4])

array(['sdf', '4', '5.4'], dtype='<U3')

In [5]:
np.array([1, 2, 3.0])
#when one element is folat, all elements are converted to float (upcasting)

array([1., 2., 3.])

### multi dimensional array

In [8]:
#2d array
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [10]:
#specifying min dimension
np.array([1,2,3,4], ndmin=2)

array([[1, 2, 3, 4]])

### specifying data type of array

In [11]:
np.array([1, 2, 3], dtype=complex)


array([1.+0.j, 2.+0.j, 3.+0.j])

In [15]:
x = np.array([(1,2),(3,4)],dtype=[('a','<i2'),('b','<i8')])
#here a=1,3 b=2,4
x

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [21]:
x['a']

array([1, 3], dtype=int16)

In [22]:
x['b']

array([2, 4], dtype=int64)

In [16]:
type(x[1][0])

numpy.int16

In [17]:
type(x[0][1])

numpy.int64

In [18]:
y = np.array([(1,2),(3,4)],dtype=[('a','<f4'),('b','<i8')])
y

array([(1., 2), (3., 4)], dtype=[('a', '<f4'), ('b', '<i8')])

In [20]:
type(y[0][0])

numpy.float32

## mat()

In [27]:
np.mat('1 2; 3 4')

matrix([[1, 2],
        [3, 4]])

In [39]:
n = np.mat('1 2 3;4 5 6; 7 8 9')
n

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [26]:
#from array
m = np.mat(np.array([[1, 2],[4,7]]))
#interpret the input as a matrix
print(type(m))
m

<class 'numpy.matrix'>


matrix([[1, 2],
        [4, 7]])

In [31]:
#we can also convert matrix back to array
np.array(np.mat('1 2; 3 4'))

array([[1, 2],
       [3, 4]])

### Accessing matrix elements

In [43]:
n

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [40]:
n[0]
#0th row

matrix([[1, 2, 3]])

In [41]:
n[0,1]
#0th row, first column

2

In [44]:
#row 1, col 0
n[1,0]

4

In [46]:
#rows 0 and 1, col 2
n[0:2,2]

matrix([[3],
        [6]])

### Accessing array elements

In [47]:
arr = np.array([[1, 2], [3, 4]])
arr

array([[1, 2],
       [3, 4]])

In [48]:
arr[0]

array([1, 2])

In [49]:
arr[0][0]

1

In [50]:
arr[0,0]

1

In [51]:
arr[:,1]

array([2, 4])

## asarray()

In [53]:
#Convert the input to an array.
a = [1, 2]
arr_a = np.asarray(a)
print(type(arr_a))
arr_a


<class 'numpy.ndarray'>


array([1, 2])

In [54]:
np.asarray(a, dtype=np.float64)

array([1., 2.])

## asanyarray()

In [55]:
np.asanyarray(a)

array([1, 2])

In [58]:
x = np.matrix([1,2])
x

matrix([[1, 2]])

In [60]:
np.asanyarray(x)
#matrix is already a type of array. No changes made

matrix([[1, 2]])

## numpy array object properties and methods

In [78]:
#get the dimension of the array
a = np.array([2,3,4])
print(a.shape)
print(a.ndim)
a.size

(3,)
1


3

In [81]:
b = np.array([[1, 2], [3, 4]])
print("Type/Class of this object:",type(b))
print("Here is the matrix\n----------\n",b,"\n----------")
print("Dimension of this matrix: ",b.ndim,sep='') #ndim gives the dimensison, 2 for a matrix, 1 for a vector
print("Size of this matrix: ", b.size,sep='') #size gives the total number of elements
print("Shape of this matrix: ", b.shape,sep='') #shape gives the number of elements along each axes (dimension)
print("Data type of this matrix: ", b.dtype,sep='') #dtype gives the data type contained in the array

Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2]
 [3 4]] 
----------
Dimension of this matrix: 2
Size of this matrix: 4
Shape of this matrix: (2, 2)
Data type of this matrix: int32


## Shallow and deep copy

In [61]:
x = np.array([1, 2, 3])
print("Value of x", x)
y = x
#changes in one will affect the other. only one copy exist
print("value of y", y)
y[0] = 5
print("After modifying y, value of x", x)
print("After modifying y, value of y", y)

Value of x [1 2 3]
value of y [1 2 3]
After modifying y, value of x [5 2 3]
After modifying y, value of y [5 2 3]


In [62]:
z = np.copy(x)
#deep copy; a new location z will contain the value. changes will not affect each other
z[0] = 7
print("Value of z", z)
print("Value of x", x)

Value of z [7 2 3]
Value of x [5 2 3]


## fromfunction()

In [65]:
#Construct an array by executing a function over each element.
np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [67]:
np.fromfunction(lambda i, j: i * j, (4, 3), dtype=float)

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.],
       [0., 3., 6.]])

## fromiter()

In [68]:
#Create a new 1-dimensional array from an iterable object.
iterable = (x*x for x in range(5))
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [69]:
np.fromiter(range(10), int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
np.fromiter(list(range(10)), int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## fromstring()

In [74]:
#A new 1-D array initialized from text data in a string
a = np.fromstring('234 234', dtype=int, sep=' ')
a

array([234, 234])

In [75]:
np.fromstring('1, 2', sep=',')

array([1., 2.])

## linspace()

In [84]:
print("21 linearly spaced numbers between 1 and 5\n--------------------------------------------")
print((np.linspace(1,5,21)))

21 linearly spaced numbers between 1 and 5
--------------------------------------------
[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4
 4.6 4.8 5. ]


In [99]:
np.linspace(2.0, 3.0, num=5)
#here end number 3 is included

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [100]:
np.linspace(2.0, 3.0, num=5, endpoint=False)
#end point not included

array([2. , 2.2, 2.4, 2.6, 2.8])

In [102]:
np.linspace(2.0, 4.0, num=9, retstep=True)
#displays the distance between data as well

(array([2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 , 3.75, 4.  ]), 0.25)

## logspace()

In [103]:
np.logspace(2.0, 3.0, num=4,base = 10)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [104]:
np.logspace(2.0, 3.0, num=4, endpoint=False)

array([100.        , 177.827941  , 316.22776602, 562.34132519])

In [105]:
np.logspace(2.0, 3.0, num=4, base=2.0)

array([4.        , 5.0396842 , 6.34960421, 8.        ])

## Matrix creation

## zeros()

In [85]:
print("Vector of zeroes\n---------------------")
print(np.zeros(5))

Vector of zeroes
---------------------
[0. 0. 0. 0. 0.]


In [86]:
print("Matrix of zeroes\n--------------------")
print(np.zeros((3,4))) # Notice Tuples

Matrix of zeroes
--------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## ones()

In [87]:
print("Vector of ones\n---------------------")
print(np.ones(5))

Vector of ones
---------------------
[1. 1. 1. 1. 1.]


In [88]:
print("Matrix of ones\n---------------------")
print(np.ones((3,2,8))) # Note matrix dimension specified by Tuples


Matrix of ones
---------------------
[[[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]]


In [89]:
print("Matrix of 5's\n---------------------")
print(4+np.ones((3,5)))

Matrix of 5's
---------------------
[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


In [91]:
c = 5*np.ones((3,5))
c

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

## empty()

In [97]:
np.empty((3,5))

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

## Identity matrix creation .eye()

In [98]:
mat1 = np.eye(4) 
print("Identity matrix of dimension", mat1.shape)
print(mat1)

Identity matrix of dimension (4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## reshape()

In [106]:
print(np.arange(16))
x = np.arange(16).reshape((-1,4))
x
#with one -ve and one correct number, it will work fine

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [110]:
x = np.arange(16).reshape((3,4))
x
#with 2 +ve numbers, if the dimension is not enough to contain the elements, error

ValueError: cannot reshape array of size 16 into shape (3,4)

In [112]:
x = np.arange(16).reshape((-1,2))
x

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

## diag()

In [114]:
np.diag(x)
# prints the diagonal elements of a matrix

array([0, 3])

In [115]:
x = np.arange(16).reshape((-1,4))
print(x)
np.diag(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([ 0,  5, 10, 15])

In [116]:
np.diag(x, k=1)
#`k>0` for diagonals above the main diagonal, 
#`k<0` for diagonals below the main diagonal.

array([ 1,  6, 11])

In [117]:
np.diag(x, k=2)

array([2, 7])

In [118]:
np.diag(x, k=3)

array([3])

In [119]:
np.diag(x, k=4)

array([], dtype=int32)

In [120]:
np.diag(x, k=-1)

array([ 4,  9, 14])

### make non diagonal elements 0

In [121]:
x = np.arange(16).reshape((-1,4))
np.diag(np.diag(x))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

## diagflat()

In [123]:
#Create a two-dimensional array with the flattened input as a diagonal.
np.diagflat([[1,2], [3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [125]:
# k = Diagonal to set; 0, the default, corresponds to the "main" diagonal,
#a positive (negative) `k` giving the number of the diagonal above (below) the main.
np.diagflat([1,2], k=1)

array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

In [126]:
np.diagflat([1,2], k=-1)

array([[0, 0, 0],
       [1, 0, 0],
       [0, 2, 0]])

## Triangle matrices .tri()

np.tri(N, M=None, k=0, dtype=<class 'float'>)

N : int
    Number of rows in the array.
    
M : int, optional
    Number of columns in the array.
    By default, `M` is taken equal to `N`.
    
k : int, optional
    The sub-diagonal at and below which the array is filled.
    `k` = 0 is the main diagonal, while `k` < 0 is below it,
    and `k` > 0 is above.  The default is 0.
    
dtype : dtype, optional
    Data type of the returned array.  The default is float

In [127]:
np.tri(3, 5, 1, dtype=int)

array([[1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0]])

In [128]:
np.tri(3, 5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

### lower triangle tril()

In [129]:
np.tril([[1,2,3],[4,5,6],[7,8,9]], 0)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

### upper triangle triu()

In [130]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0],
       [0, 0, 0]])

# Random number generation

### uniform distribution rand()

In [131]:
print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

Random number generation (from Uniform distribution)
[[0.84773242 0.58683938 0.51268054]
 [0.47993397 0.81452973 0.16845655]]


### normal distribution

In [133]:
print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[ 0.8497777   0.15798282  0.18756469]
 [-1.85164066 -1.15284438 -1.70449305]
 [ 1.02307459  0.08228204  0.81810392]
 [ 1.01212916 -1.035683   -1.43167273]]


### random int vector and matrix

In [137]:
print("Random integer vector:",np.random.randint(1,10,9)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")
print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)
#size can be specified as dimension in the form of tuple
np.random.randint(1,10,9).reshape(3,3) #another way of creating matrix

Random integer vector: [5 6 9 6 4 4 4 6 5]

Random integer matrix
[[46 69 42 53]
 [10 43 84 36]
 [75 78 11 91]
 [40 81 37 27]]


array([[9, 5, 8],
       [2, 4, 8],
       [1, 2, 3]])

In [138]:
print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw


20 samples drawn from a dice throw: [2 3 4 1 6 4 2 2 2 3 5 2 5 6 2 3 1 4 4 1]


## sort()

In [139]:
from numpy.random import randint as ri
A = ri(1,100,10) # Vector of random interegrs
print("\nVector of random integers\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))


Vector of random integers
 -------------------------------------------------- 
 [45  5 76 66 80 20 60 83 63 51]

Here is the sorted vector
 -------------------------------------------------- 
 [ 5 20 45 51 60 63 66 76 80 83]


In [144]:
#sorting of matrix
M = ri(1,100,25).reshape(5,5) # Matrix of random interegrs
print(M)
# Default axis =None flaten matrix and sort it
print("\nHere is the sorted matrix after flatening\n",'-'*50,"\n",np.sort(M, axis=None, kind='mergesort')) 
#axis= 1 sort row-wise
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M, axis=1, kind='mergesort'))
#axis = 0 column-wise
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=0, kind='mergesort'))

[[83 73 39 49 53]
 [77 32 26 43 44]
 [24 57 77 38 89]
 [19 46 88 75 62]
 [98 77  4  2 62]]

Here is the sorted matrix after flatening
 -------------------------------------------------- 
 [ 2  4 19 24 26 32 38 39 43 44 46 49 53 57 62 62 73 75 77 77 77 83 88 89
 98]

Here is the sorted matrix along each row
 -------------------------------------------------- 
 [[39 49 53 73 83]
 [26 32 43 44 77]
 [24 38 57 77 89]
 [19 46 62 75 88]
 [ 2  4 62 77 98]]

Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[19 32  4  2 44]
 [24 46 26 38 53]
 [77 57 39 43 62]
 [83 73 77 49 62]
 [98 77 88 75 89]]


## Find max and min of array

In [146]:
A = ri(1,100,10)
print(A)
A.max()

[26 83 22 85 65 14 79 94 23 11]


94

In [147]:
M = ri(1,100,25).reshape(5,5)
print(M)
M.min()

[[21 84 58  5 91]
 [28 27 98 84 68]
 [71 26 86  4 32]
 [22 80 88 49 36]
 [39 23 36 74 42]]


4

In [150]:
A.argmax()
#return position of max element

7

## Indexing and slicing

In [154]:
#Indexing examples

arr = np.arange(0,11)
print("Array:",arr)

print("Element at 7th index is:", arr[7])

print("Alternate Elements from 3rd to 5th index are:", arr[3:6:2])

print("Elements up to 4th index are:", arr[:4])

print("Elements from last backwards are:", arr[-1:7:-1])

print("Alternate Elements from last backwards are:", arr[-1::-2])

Array: [ 0  1  2  3  4  5  6  7  8  9 10]
Element at 7th index is: 7
Alternate Elements from 3rd to 5th index are: [3 5]
Elements up to 4th index are: [0 1 2 3]
Elements from last backwards are: [10  9  8]
Alternate Elements from last backwards are: [10  8  6  4  2  0]


In [156]:
#Slicing examples

arr = np.arange(0,21,2)
print("New array:",arr)

print("Elements at 2nd, 4th, and 9th index are:", arr[[2,4,9]]) # Pass a list as a index to subset

New array: [ 0  2  4  6  8 10 12 14 16 18 20]
Elements at 2nd, 4th, and 9th index are: [ 4  8 18]


In [160]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
print("\nMatrix subset,rows 1 and 2,col 3,4\n","-"*25,"\n",mat[1:4,3:5])
mat[0:3,[1,3]]

Matrix of random 2-digit numbers
--------------------------------
 [[70 19 35 51 51]
 [31 73 58 85 23]
 [55 70 46 46 72]]

Matrix subset,rows 1 and 2,col 3,4
 ------------------------- 
 [[85 23]
 [46 72]]


array([[19, 51],
       [73, 85],
       [70, 46]])

In [161]:
print("\nDouble bracket indexing\n------------------------")
print(mat)
print("Element in row index 1 and column index 2:", mat[1][1])



Double bracket indexing
------------------------
[[70 19 35 51 51]
 [31 73 58 85 23]
 [55 70 46 46 72]]
Element in row index 1 and column index 2: 73


In [162]:
print("\nSingle bracket with comma indexing\n----------------------------------")
print("Element in row index 1 and column index 2:", mat[1,2])
print("\nRow or column extract\n----------------------")
mat[1]


Single bracket with comma indexing
----------------------------------
Element in row index 1 and column index 2: 58

Row or column extract
----------------------


array([31, 73, 58, 85, 23])

In [163]:
print("Entire column at index 3:", mat[:,3])

Entire column at index 3: [51 85 46]


In [164]:
print("\nSubsetting sub-matrices\n--------------------------")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:3,3:5])


Subsetting sub-matrices
--------------------------
Matrix with row indices 1 and 2 and column indices 3 and 4
 [[85 23]
 [46 72]]


In [168]:
#Another example of slicing
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)
mat_slice = mat[:2,:2]
print ("\nSliced matrix")
print(mat_slice)
print ("\nChange the sliced matrix")
mat_slice[0,0] = 1000
print (mat_slice)
print("\nBut the original matrix? WHOA! It got changed too!")
print(mat)

Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]

Sliced matrix
[[11 12]
 [21 22]]

Change the sliced matrix
[[1000   12]
 [  21   22]]

But the original matrix? WHOA! It got changed too!
[[1000   12   13]
 [  21   22   23]
 [  31   32   33]]


In [169]:
# Little different way to create a copy of the sliced matrix
print ("\nDoing it again little differently now...\n")
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)
mat_slice = np.array(mat[:2,:2]) # Notice the np.array command to create a new array not just slicing
print ("\nSliced matrix")
print(mat_slice)
print ("\nChange the sliced matrix")
mat_slice[0,0] = 1000
print (mat_slice)
print("\nBut the original matrix? NO CHANGE this time:)")
print(mat)


Doing it again little differently now...

Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]

Sliced matrix
[[11 12]
 [21 22]]

Change the sliced matrix
[[1000   12]
 [  21   22]]

But the original matrix? NO CHANGE this time:)
[[11 12 13]
 [21 22 23]
 [31 32 33]]


### Subsetting matrix based on condition

In [165]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
mat>50

Matrix of random 2-digit numbers
--------------------------------
 [[76 41 32 28 11]
 [30 83 41 64 75]
 [88 54 22 86 67]]


array([[ True, False, False, False, False],
       [False,  True, False,  True,  True],
       [ True,  True, False,  True,  True]])

In [167]:
print ("Elements greater than 50\n", mat[mat>50])

Elements greater than 50
 [76 83 64 75 88 54 86 67]


### Extract specific rows based on a condition 
_np.where(condition)_

In [16]:
titanic_train = pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",
                           sep='\t') 
#find indexes of rows with Age=null
missing = np.where(titanic_train['Age'].isnull()==True)
print(missing)
titanic_train.loc[missing]

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
        48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
       126, 128, 140, 154], dtype=int64),)


PassengerId  Survived  Pclass  \
5              6         0       3   
17            18         1       2   
19            20         1       3   
26            27         0       3   
28            29         1       3   
29            30         0       3   
31            32         1       1   
32            33         1       3   
36            37         1       3   
42            43         0       3   
45            46         0       3   
46            47         0       3   
47            48         1       3   
48            49         0       3   
55            56         1       1   
64            65         0       1   
65            66         1       3   
76            77         0       3   
77            78         0       3   
82            83         1       3   
87            88         0       3   
95            96         0       3   
101          102         0       3   
107          108         1       3   
109          110         1       3   
121          122         0       3   
126          127         0       3   
128          129         1       3   
140          141         0       3   
154          155         0       3   

                                               Name     Sex  Age  SibSp  \
5                                  Moran, Mr. James    male  NaN      0   
17                     Williams, Mr. Charles Eugene    male  NaN      0   
19                          Masselmani, Mrs. Fatima  female  NaN      0   
26                          Emir, Mr. Farred Chehab    male  NaN      0   
28                    O'Dwyer, Miss. Ellen "Nellie"  female  NaN      0   
29                              Todoroff, Mr. Lalio    male  NaN      0   
31   Spencer, Mrs. William Augustus (Marie Eugenie)  female  NaN      1   
32                         Glynn, Miss. Mary Agatha  female  NaN      0   
36                                 Mamee, Mr. Hanna    male  NaN      0   
42                              Kraeff, Mr. Theodor    male  NaN      0   
45                         Rogers, Mr. William John    male  NaN      0   
46                                Lennon, Mr. Denis    male  NaN      1   
47                        O'Driscoll, Miss. Bridget  female  NaN      0   
48                              Samaan, Mr. Youssef    male  NaN      2   
55                                Woolner, Mr. Hugh    male  NaN      0   
64                            Stewart, Mr. Albert A    male  NaN      0   
65                         Moubarek, Master. Gerios    male  NaN      1   
76                                Staneff, Mr. Ivan    male  NaN      0   
77                         Moutal, Mr. Rahamin Haim    male  NaN      0   
82                   McDermott, Miss. Brigdet Delia  female  NaN      0   
87                    Slocovski, Mr. Selman Francis    male  NaN      0   
95                      Shorney, Mr. Charles Joseph    male  NaN      0   
101                Petroff, Mr. Pastcho ("Pentcho")    male  NaN      0   
107                          Moss, Mr. Albert Johan    male  NaN      0   
109                             Moran, Miss. Bertha  female  NaN      1   
121                      Moore, Mr. Leonard Charles    male  NaN      0   
126                             McMahon, Mr. Martin    male  NaN      0   
128                               Peter, Miss. Anna  female  NaN      1   
140                   Boulos, Mrs. Joseph (Sultana)  female  NaN      0   
154                           Olsen, Mr. Ole Martin    male  NaN      0   

     Parch           Ticket      Fare  Cabin Embarked  
5        0           330877    8.4583    NaN        Q  
17       0           244373   13.0000    NaN        S  
19       0             2649    7.2250    NaN        C  
26       0             2631    7.2250    NaN        C  
28       0           330959    7.8792    NaN        Q  
29       0           349216    7.8958    NaN        S  
31       0         PC 17569  146.5208    B78        C  
32       0           335677    7.7500    NaN        

# Universal Functions

## Elementwise arithmetic operation

In [172]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)



1st Matrix of random single-digit numbers
----------------------------------------
 [[3 2 2]
 [6 6 8]
 [5 9 8]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[7 1 6]
 [7 3 4]
 [1 7 7]]


In [176]:
mat1-mat2

array([[-4,  1, -4],
       [-1,  3,  4],
       [ 4,  2,  1]])

In [173]:
mat1*mat2

array([[21,  2, 12],
       [42, 18, 32],
       [ 5, 63, 56]])

In [175]:
print("\nMultiplication\n------------------\n", mat1@mat2)


Multiplication
------------------
 [[ 37  23  40]
 [ 92  80 116]
 [106  88 122]]


In [178]:

print("\nLineaer combination: 3*A - 2*B\n-----------------------------\n", 3*mat1-2*mat2)


Lineaer combination: 3*A - 2*B
-----------------------------
 [[-5  4 -6]
 [ 4 12 16]
 [13 13 10]]


In [179]:
print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1)


Addition of a scalar (100)
-------------------------
 [[103 102 102]
 [106 106 108]
 [105 109 108]]


In [180]:
print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, using pow function\n-------------------------------------------\n",pow(mat1,3))


Exponentiation, matrix cubed here
----------------------------------------
 [[ 27   8   8]
 [216 216 512]
 [125 729 512]]

Exponentiation, sq-root using pow function
-------------------------------------------
 [[ 27   8   8]
 [216 216 512]
 [125 729 512]]


# Broadcasting

In [181]:
start = np.zeros((4,4))
print("Start Matrix\n","-"*30,"\n",start)
start= start+100
print("After full broadcast\n","-"*30,"\n",start)


Start Matrix
 ------------------------------ 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
After full broadcast
 ------------------------------ 
 [[100. 100. 100. 100.]
 [100. 100. 100. 100.]
 [100. 100. 100. 100.]
 [100. 100. 100. 100.]]


In [182]:
#row wise broadcast
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2, 5])
print(add_rows)
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

[1 0 2 5]
[[101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]]


In [183]:
#column wise broadcast
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
print(add_cols)
# this will just broadcast in both dimensions
add_scalar = np.array([100])  
print(start+y)

[[0]
 [1]
 [2]
 [3]]
[[201. 200. 202. 205.]
 [201. 200. 202. 205.]
 [201. 200. 202. 205.]
 [201. 200. 202. 205.]]


# Array Math

In [185]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n------------\n",mat2)

print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))

print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))

print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))

print("\nModulo reminder using np\n",'-'*50,"\n", np.fmod(mat1,mat2))


1st Matrix of random single-digit numbers

 [[3 8 3]
 [5 9 4]
 [8 2 4]]

2nd Matrix of random single-digit numbers
------------
 [[1 2 2]
 [5 9 5]
 [3 6 7]]

Sq-root of 1st matrix using np
------------------
 [[1.73205081 2.82842712 1.73205081]
 [2.23606798 3.         2.        ]
 [2.82842712 1.41421356 2.        ]]

Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[2.00855369e+01 2.98095799e+03 2.00855369e+01]
 [1.48413159e+02 8.10308393e+03 5.45981500e+01]
 [2.98095799e+03 7.38905610e+00 5.45981500e+01]]

10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.47712125 0.90308999 0.47712125]
 [0.69897    0.95424251 0.60205999]
 [0.90308999 0.30103    0.60205999]]

Modulo reminder using np
 -------------------------------------------------- 
 [[0 0 1]
 [0 0 4]
 [2 2 4]]


In [188]:
print("\nCombination of functions by shwoing exponetial decay of a sine wave\n",'-'*70)
A = np.linspace(0,12*np.pi,1001)
A


Combination of functions by shwoing exponetial decay of a sine wave
 ----------------------------------------------------------------------


array([ 0.        ,  0.03769911,  0.07539822, ..., 37.62371362,
       37.66141273, 37.69911184])