<h1 align='center'> Numpy methods </h1>

In [3]:
import numpy as np

## arange()

In [9]:
#range() like function that accepts float 
print(np.arange(5))
np.arange(0.1,0.9,0.2)

[0 1 2 3 4]


array([0.1, 0.3, 0.5, 0.7])

In [8]:
np.arange(2,1,-0.3)

array([2. , 1.7, 1.4, 1.1])